oasis-open/cti-stix-validator

- validator/validators.py
If a KeyError was thrown, the validator output would consist of merely the name of the key that was not found. This isn't very helpful to the user, and the cause of the error should be caught by the schemas anyway.
> Fix KeyErrors and ambiguous validation errors

- README.rst
- stix2validator/__init__.py
- stix2validator/enums.py
- stix2validator/output.py
- stix2validator/scripts/stix2_validator.py
- stix2validator/test/indicator_tests.py
- stix2validator/test/relationship_tests.py
- stix2validator/validators.py
- Improve error messages
- omit u' prefix on strings
- use an object id or schema path to identify what caused the error
- Update checks to RC3 (partial)
- relationship types common to all objects
- some enum values
- Make the validator easier to use 
- installation notes
- better passing of arguments when used as an imported library, such as in the stix elevator
> Bug fixes and improvements

- stix2validator/__init__.py
- stix2validator/enums.py
- stix2validator/scripts/stix2_validator.py
- stix2validator/test/bundle_tests.py
- stix2validator/test/identity_tests.py
- stix2validator/test/indicator_tests.py
- stix2validator/test/marking_definition_tests.py
- stix2validator/test/observed_data_tests.py
- stix2validator/validators.py
- Remove 'pattern_lang'
- Remove location attributes
- Switch to 'objects' in bundles instead of separate properties for each object type
- Prevent marking circular definitions
- Ensure marking selectors refer to items actually in the object
- Produce warnings/errors for _all_ instances of certain categories instead of just the first one
Closes #6.
> Update to more current version of RC3

- stix2validator/musts.py
- stix2validator/shoulds.py
- stix2validator/test/network_traffic_tests.py
- stix2validator/test/observed_data_tests.py
Fix #12.
STIX content that passes validation when the cache is used may fail validation when the cache is not used, because in the latter case a regex is used instead of checking a list. Values not in the list may still match the regex.
> Update tests to work offline

- .gitignore
- .travis.yml
- setup.py
- stix2validator/enums.py
- stix2validator/musts.py
- stix2validator/scripts/stix2_validator.py
- stix2validator/shoulds.py
- stix2validator/test/__init__.py
- stix2validator/test/attack_pattern_tests.py
- stix2validator/test/custom_obj_tests.py
- stix2validator/test/indicator_tests.py
- stix2validator/test/marking_definition_tests.py
- stix2validator/test/observed_data_tests.py
- stix2validator/test/relationship_tests.py
- tox.ini
- expanded tests
- and added Python 3.6 to CI
- integrated the pattern validator
- bug fixes
- threat-actor.goals was incorrectly defined as an open vocabulary
- added some reserved properties that were left out
- the validator will search input directories recursively by default now
Note: Python 2.6 was removed from Tox when the pattern validator was integrated because the Python ANTLR library does not support it.
> Miscellaneous improvements

- README.rst
- stix2validator/enums.py
- stix2validator/errors.py
- stix2validator/musts.py
- stix2validator/scripts/stix2_validator.py
- stix2validator/shoulds.py
- stix2validator/test/attack_pattern_tests.py
- stix2validator/test/custom_obj_tests.py
- stix2validator/test/indicator_tests.py
- stix2validator/test/observed_data_tests.py
- stix2validator/validator.py
Does not check properties of extensions or embedded objects. That will be possible once `stix2patterns` has been updated so the `inspect()` method gives more granular details.
Note that this PR removes some check codes; `custom-property-prefix`, `custom-observable-object-prefix,` `custom-object-extension-prefix`, `custom-observable-properties-prefix`, and their `-lax` siblings have been replaced with `custom-prefix` and `custom-prefix-lax`.
Fix #23.
> Validate custom object types and properties in patterns

- stix2validator/musts.py
- stix2validator/test/indicator_tests.py
- one caused by recent pattern-validator update
- one caused by backslashes
Close #29.
> Fix patterning bugs

- tox.ini
It seems codecov is unable to find the coverage report. Hopefully this change will fix that.
> Update Tox configuration.

- setup.py
I have run into an issue where my project requires newer `jsonschema` than stix validator had pinned in its dependencies. To prevent having rerelease `stix2-validator` every time `jsonschema` makes a backward compatible update that someone wants to use as well as `stix2-validator` I suggest allowing any version that fulfills minimal `stix2-validator`requirements.
> unpin jsonschema version

- stix2validator/musts.py
- stix2validator/shoulds.py
- stix2validator/test/relationship_tests.py
- stix2validator/util.py
Added a command-line feature (--enforce_refs) which users to get a warning message when not all SDOs referenced by SROs are contained in the same bundle.
> Addressing Issue #72: Enforce referenced objects in relationship objects

- docs/best-practices.rst
- stix2validator/util.py
- stix2validator/v21/enums.py
- stix2validator/v21/shoulds.py
These treat opinion-emum and encryption_algo_enum as if they were open
vocabs instead.
Fixes #104.
> Remove checks 229 and 242

- stix2validator/test/v21/indicator_tests.py
- stix2validator/v21/musts.py
Prevents calling the stix2 pattern validator for non-stix `pattern_type`.
closes #99
> add check for 'pattern_type' indicator

- stix2validator/validator.py
`jsonschema`'s built-in email format checker only ensures it contains the '@' character. We want a more robust check. Moved it here instead of schemas to rely on JSON Schema spec's 'email' format for users of other JSON Schema validators in other languages.
> Ensure emails are formatted correctly.

- stix2validator/v21/enums.py
> Add 'swid' as a legal property of the 2.1 'software' SCO.

- stix2validator/test/v21/observed_data_tests.py
- stix2validator/util.py
- stix2validator/v21/shoulds.py
Warnings about SCO types were incorrectly attributed to the Observed Data object that contained them in the deprecated `objects` property.
> Fix bug with 2.1 observed-data.objects

- stix2validator/errors.py
- stix2validator/test/v21/malware_tests.py
Reference: https://github.com/oasis-open/cti-stix2-json-schemas/issues/134
> Reword malware.is_family error if it's not boolean

- stix2validator/errors.py
Specifically, when 'is_family' is true but 'name' is not present. Fixes #163.
> Improve an error message for malware

- stix2validator/test/v21/network_traffic_tests.py
- stix2validator/test/v21/sighting_tests.py
- stix2validator/v21/enums.py
Two sets of timestamp properties were change to allow both properties in the set to have the exact same timestamp:
- Sighting: first_seen and last_seen
- Network Traffic: start and end
> Fix timestamp comparisons for CS03

- setup.py
- stix2validator/test/v21/observed_data_tests.py
Reason the change is needed: https://github.com/python-jsonschema/jsonschema/issues/962
> Fix jsonschema version extras

- stix2validator/test/v21/indicator_tests.py
- stix2validator/test/v21/test_schemas/extension-definition--993ce403-6fdd-4efa-8279-31cf2d91b1c8.json
- stix2validator/validator.py
This lets you use multiple extensions for the same object type, or extensions that extend multiple object types.
> Allow custom schemas to use extension def ids

- docs/usage.rst
- stix2validator/errors.py
- stix2validator/output.py
- stix2validator/test/v21/indicator_tests.py
- stix2validator/validator.py
- Allow symlinks to folders in the directory given to the `--schemas` option.
- Revise documentation on using additional schemas.
- Revise an error message that may come up when using a schema for an extension and failing its validation.
> Update for extension schemas

- setup.py
Can this constraint be removed if there isn't a clear dependency or use case for the constraint?
The attrs constraint was added in #191 but the stix2-validator does not use that package directly.
In that delta the jsonschema package version is modified. The latest release of the jsonschema package required attrs>=17.4.0,  https://github.com/python-jsonschema/jsonschema/blob/v4.17.3/pyproject.toml#L35
The next release of the jsonschema package will require attrs >= 22.2.0. The current constraint will prevent users from being able to upgrade their jsonschema library when that is released.
> Remove the attrs constraint added by #191

- README.rst
Hey, while scrolling through the README I randomly clicked on @rpiazza profile link which led to the GitHub 404 page due to a trailing `)`.
This PR simply removes it :)
> fix: @rpiazza GitHub profile link

- .github/workflows/python-ci-tests.yml
Since we do path manipulation when processing JSON files (functionality further exercised by this PR https://github.com/oasis-open/cti-stix-validator/pull/228), tests should run at least once on Windows to make sure that path manipulation works as expected.
CC @clenk
> Run latest Python tests on Windows

- stix2validator/test/v21/misc_tests.py
- stix2validator/test/v21/test_examples/identity_unicode.json
- stix2validator/validator.py
Previously undetected because testing was only performed on systems where utf-8 is default.
> Fix unicode errors when validating files

- .readthedocs.yaml
Should fix broken RTD doc builds. Needed because of https://blog.readthedocs.com/migrate-configuration-v2/
@rpiazza
> Add required ReadTheDocs configuration
