- .gitignore
- README.rst
- stix2validator/enums.py
- stix2validator/errors.py
- stix2validator/scripts/stix2_validator.py
- stix2validator/shoulds.py
- stix2validator/test/observed_data_tests.py
- stix2validator/test/vulnerability_tests.py
- stix2validator/util.py
> Update to WD02

- .isort.cfg
- .pre-commit-config.yaml
- .travis.yml
- setup.py
- stix2validator/validator.py
- tox.ini
> Use appdirs for platform-specific cache location

- stix2validator/__init__.py
- stix2validator/codes.py
- stix2validator/output.py
- stix2validator/scripts/stix2_validator.py
- stix2validator/test/__init__.py
- stix2validator/test/attack_pattern_tests.py
- stix2validator/test/bundle_tests.py
- stix2validator/test/custom_obj_tests.py
- stix2validator/test/identity_tests.py
- stix2validator/test/indicator_tests.py
- stix2validator/test/intrusion_set_tests.py
- stix2validator/test/malware_tests.py
- stix2validator/test/marking_definition_tests.py
- stix2validator/test/multi_obj_test.py
- stix2validator/test/network_traffic_tests.py
- stix2validator/test/observed_data_tests.py
- stix2validator/test/relationship_tests.py
- stix2validator/test/report_tests.py
- stix2validator/test/sighting_tests.py
- stix2validator/test/threat_actor_tests.py
- stix2validator/test/tool_tests.py
- stix2validator/test/vulnerability_tests.py
- stix2validator/validator.py
(I felt like I was stomping over the code more when I wrote this; that's why the branch name is "*_stomped".)
So this is a first cut.  I want to add more comments inline with the code too, within this PR, to help explain changes.
> Changes to enable validation of files with lists of objects

- .gitignore
- stix2validator/__init__.py
- stix2validator/output.py
- stix2validator/scripts/stix2_validator.py
> Use 'logging' instead of 'print'

- stix2validator/errors.py
- stix2validator/test/observed_data_tests.py
Updates the bundled schemas to the latest version, which fixes the URL regex pattern.
> Url pattern update

- stix2validator/scripts/stix2_validator.py
- stix2validator/test/bundle_tests.py
- stix2validator/util.py
> Handle "verbose" and "silent" options correctly

- README.rst
- docs/Makefile
- docs/best-practices.rst
- docs/conf.py
- docs/index.rst
- docs/install.rst
- docs/options.rst
- docs/usage.rst
> Create Sphinx documentation

- stix2validator/__init__.py
> Allow validate_instance to be imported

- stix2validator/__init__.py
- stix2validator/output.py
- stix2validator/scripts/stix2_validator.py
- stix2validator/test/indicator_tests.py
- stix2validator/test/misc_tests.py
- stix2validator/test/test_examples/identity.json
- stix2validator/test/test_examples/identity_custom.json
- stix2validator/test/test_examples/identity_warning.json
- stix2validator/test/test_examples/invalid_braces.json
- stix2validator/test/test_examples/invalid_comma.json
- stix2validator/test/test_examples/invalid_identity.json
- stix2validator/test/test_examples/invalid_timestamp.json
- stix2validator/validator.py
> Allow printing of ObjectValidationResults

- stix2validator/validator.py
See https://github.com/oasis-open/cti-stix-validator/pull/69#issuecomment-407897214.
> Sort files

- stix2validator/test/observed_data_tests.py
- stix2validator/validator.py
Addressed issue #80 by adding a direct error message for when an Observed Data object's object property is not in dictionary format.
> Enhancement: Issue #80 Observed Data

- stix2validator/test/v21/network_traffic_tests.py
> Updating tests for stix2 WD06

- docs/best-practices.rst
- stix2validator/test/v21/indicator_tests.py
- stix2validator/util.py
- stix2validator/v21/enums.py
- stix2validator/v21/shoulds.py
- tox.ini
Align `HASH_ALGO_OV` with latest vocab, add check for `pattern-type-ov`
> Update hash-algorithm-ov, pattern-type-ov

- docs/best-practices.rst
Updating best-practices.rst to include both mandatory and optional error and warning messages.
> updating best-practices.rst to include error and warning messages

- stix2validator/validator.py
> Empty default schema check

- stix2validator/v21/musts.py
Makes it clear where the errors are originating from.
Fixes #119.
> Fix some musts' error messages

- setup.py
- stix2validator/validator.py
Previously they would be ignored.
> Allow "format" fields in schemas

- stix2validator/test/v21/observed_data_tests.py
- stix2validator/v21/musts.py
- stix2validator/v21/shoulds.py
> Ensure custom extension names end in '-ext'

- stix2validator/test/v21/observed_data_tests.py
- stix2validator/v21/enums.py
Remove some of un-deprecated properties
closes #123
> Update deprecated properties

- docs/best-practices.rst
- stix2validator/test/v21/custom_obj_tests.py
- stix2validator/v21/enums.py
- stix2validator/v21/musts.py
add check for first letter lowercase ASCII
closes #126
> Type and Property Checks

- stix2validator/test/v21/location_tests.py
- stix2validator/v21/enums.py
> Fix latitude typo

- stix2validator/test/v21/tool_tests.py
- stix2validator/v21/shoulds.py
> Don't error out on invalid UUID

- docs/usage.rst
- stix2validator/validator.py
Improved documentation for additional schemas
> Explain additional schemas

- docs/contributing.rst
Also add instructions for how to update the schemas
> Update schemas to be more lenient with Windows registry keys

- .github/workflows/python-ci-tests.yml
- setup.py
- tox.ini
updates test harness to test python 3.10 and not 3.6
> Test harness

- stix2validator/validator.py
> Fix DeprecationWarning about jsonschema.draft202012_format_checker

- docs/release.md
Content courtesy of MITRE and Chris Lenk.
> doc: add doc describing release steps

- stix2validator/scripts/stix2_validator.py
Fix issue https://github.com/oasis-open/cti-stix-validator/issues/225
> Initialize logger inside the main of the stix2validator script

- stix2validator/test/v21/network_traffic_tests.py
> Update 2.1 schemas

- CHANGELOG
> Update changelog for v3.2.0
